/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.NumComplejos;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVIDOR
 */
public class Principal3 extends javax.swing.JFrame {

    /**
     * Creates new form Principal3
     */
    public Principal3() {
        initComponents();
        cmdCalcular.setEnabled(true);
        cmdBorrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumZ1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumZ2 = new javax.swing.JTextField();
        cmbOperaciones = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtNumZ3 = new javax.swing.JTextField();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        txtNumi1 = new javax.swing.JTextField();
        txtNumi2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumi3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Operaciones con Numeros Complejos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Z1 =");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtNumZ1.setBackground(new java.awt.Color(255, 255, 204));
        txtNumZ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumZ1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 40, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Z2 =");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 30, -1));

        txtNumZ2.setBackground(new java.awt.Color(255, 255, 204));
        txtNumZ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumZ2ActionPerformed(evt);
            }
        });
        txtNumZ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumZ2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 40, 30));

        cmbOperaciones.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suma", "Resta", "Multiplicación" }));
        cmbOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOperacionesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 110, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Resultado: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        txtNumZ3.setEditable(false);
        txtNumZ3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(txtNumZ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 40, 30));

        cmdCalcular.setBackground(new java.awt.Color(255, 204, 153));
        cmdCalcular.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, 30));

        cmdBorrar.setBackground(new java.awt.Color(255, 204, 153));
        cmdBorrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, 30));

        txtNumi1.setBackground(new java.awt.Color(255, 255, 204));
        txtNumi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumi1ActionPerformed(evt);
            }
        });
        txtNumi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumi1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 30));

        txtNumi2.setBackground(new java.awt.Color(255, 255, 204));
        txtNumi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumi2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Z3 =");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        txtNumi3.setEditable(false);
        txtNumi3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(txtNumi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(511, 302));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        int opc, nz1,nz2,ni1,ni2;
        NumComplejos op1,op2,res=null;
        
        if (txtNumZ1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero entero 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumZ1.requestFocusInWindow();
            

        } else if (txtNumi1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero imaginario 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumi1.requestFocusInWindow();
            
        } else if (txtNumZ2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero entero 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumZ2.requestFocusInWindow();
            

        } else if (txtNumi2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el numero imaginario 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtNumi2.requestFocusInWindow();
           
         }else{ 
        opc=cmbOperaciones.getSelectedIndex();
        nz1=Integer.parseInt(txtNumZ1.getText());
        nz2=Integer.parseInt(txtNumZ2.getText());
        ni1=Integer.parseInt (txtNumi1.getText());
        ni2=Integer.parseInt (txtNumZ2.getText());
        
        
         op1= new NumComplejos (nz1,ni1);
         op2= new NumComplejos (nz2,ni2);
         
          switch (opc){
              case 0:
              res = op1.suma (op2);
                break;
              case 1:
                  res=op1.resta(op2);
                  break;
              case 2:
                 res=op1.multiplicacion(op2);
          }
          txtNumZ3.setText(""+res.getNumreal());
          txtNumi3.setText(""+res.getNuming());
          
          cmdCalcular.setEnabled(false);
          cmdBorrar.setEnabled(true);
        }
          
    
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtNumZ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumZ2ActionPerformed

    }//GEN-LAST:event_txtNumZ2ActionPerformed

    private void cmbOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOperacionesActionPerformed
    
    }//GEN-LAST:event_cmbOperacionesActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtNumZ1.setText("");
        txtNumZ2.setText("");
        txtNumi1.setText("");
        txtNumi2.setText("");
        txtNumZ3.setText("");
        txtNumi3.setText("");
        txtNumZ1.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);
       
        cmdCalcular.setEnabled(true);
        cmdBorrar.setEnabled(false);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtNumZ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumZ1KeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumZ1KeyTyped

    private void txtNumi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumi1ActionPerformed

    private void txtNumi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumi1KeyTyped
       char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumi1KeyTyped

    private void txtNumZ2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumZ2KeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumZ2KeyTyped

    private void txtNumi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumi2KeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c)) { 
              getToolkit().beep(); 
               
              evt.consume();    
          } 
    }//GEN-LAST:event_txtNumi2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumZ1;
    private javax.swing.JTextField txtNumZ2;
    private javax.swing.JTextField txtNumZ3;
    private javax.swing.JTextField txtNumi1;
    private javax.swing.JTextField txtNumi2;
    private javax.swing.JTextField txtNumi3;
    // End of variables declaration//GEN-END:variables
}
